"""add connect telegramm and token to users

Revision ID: 38e576acd2a4
Revises: 706ec7eda9e1
Create Date: 2026-06-15 02:21:26.783789

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '38e576acd2a4'
down_revision: Union[str, Sequence[str], None] = '706ec7eda9e1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('telegram_chat_id', sa.String(length=100), nullable=True))
    op.add_column('users', sa.Column('telegram_connect_token', sa.String(length=50), nullable=True))
    op.add_column('users', sa.Column('telegram_connected_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'telegram_connected_at')
    op.drop_column('users', 'telegram_connect_token')
    op.drop_column('users', 'telegram_chat_id')
    # ### end Alembic commands ###
