"""refactor chat_participant

Revision ID: 3aecf519b675
Revises: 4bedf95d4dbb
Create Date: 2026-04-10 19:43:27.563377

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '3aecf519b675'
down_revision: Union[str, Sequence[str], None] = '4bedf95d4dbb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chat_participants', sa.Column('user_id', sa.Integer(), nullable=True))
    op.add_column('chat_participants', sa.Column('role', sa.Enum('client', 'operator', name='participantrole'), nullable=True))
    op.create_foreign_key(None, 'chat_participants', 'users', ['user_id'], ['id'])
    op.drop_constraint(op.f('chats_ibfk_1'), 'chats', type_='foreignkey')
    op.drop_column('chats', 'assigned_to')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chats', sa.Column('assigned_to', mysql.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('chats_ibfk_1'), 'chats', 'users', ['assigned_to'], ['id'])
    op.drop_constraint(None, 'chat_participants', type_='foreignkey')
    op.drop_column('chat_participants', 'role')
    op.drop_column('chat_participants', 'user_id')
    # ### end Alembic commands ###
