"""group chats

Revision ID: 4bedf95d4dbb
Revises: b7d40e131e8a
Create Date: 2026-04-08 15:16:06.371732

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '4bedf95d4dbb'
down_revision: Union[str, Sequence[str], None] = 'b7d40e131e8a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('clients',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('external_id', sa.String(length=100), nullable=True),
    sa.Column('source', sa.Enum('telegram', 'max', name='clientsource'), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_clients_external_id'), 'clients', ['external_id'], unique=False)
    op.create_table('chat_participants',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('chat_id', sa.Integer(), nullable=True),
    sa.Column('client_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['chat_id'], ['chats.id'], ),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_index(op.f('ix_chats_id'), table_name='chats')
    op.drop_column('chats', 'client_external_id')
    op.drop_column('chats', 'client_name')
    op.add_column('messages', sa.Column('sender_user_id', sa.Integer(), nullable=True))
    op.add_column('messages', sa.Column('sender_client_id', sa.Integer(), nullable=True))
    op.add_column('messages', sa.Column('media_url', sa.String(length=255), nullable=True))
    op.add_column('messages', sa.Column('media_type', sa.String(length=20), nullable=True))
    op.drop_index(op.f('ix_messages_id'), table_name='messages')
    op.drop_constraint(op.f('messages_ibfk_2'), 'messages', type_='foreignkey')
    op.create_foreign_key(None, 'messages', 'users', ['sender_user_id'], ['id'])
    op.create_foreign_key(None, 'messages', 'clients', ['sender_client_id'], ['id'])
    op.drop_column('messages', 'sender_id')
    op.drop_column('messages', 'is_from_client')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('messages', sa.Column('is_from_client', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True))
    op.add_column('messages', sa.Column('sender_id', mysql.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'messages', type_='foreignkey')
    op.drop_constraint(None, 'messages', type_='foreignkey')
    op.create_foreign_key(op.f('messages_ibfk_2'), 'messages', 'users', ['sender_id'], ['id'])
    op.create_index(op.f('ix_messages_id'), 'messages', ['id'], unique=False)
    op.drop_column('messages', 'media_type')
    op.drop_column('messages', 'media_url')
    op.drop_column('messages', 'sender_client_id')
    op.drop_column('messages', 'sender_user_id')
    op.add_column('chats', sa.Column('client_name', mysql.VARCHAR(length=100), nullable=True))
    op.add_column('chats', sa.Column('client_external_id', mysql.VARCHAR(length=100), nullable=True))
    op.create_index(op.f('ix_chats_id'), 'chats', ['id'], unique=False)
    op.drop_table('chat_participants')
    op.drop_index(op.f('ix_clients_external_id'), table_name='clients')
    op.drop_table('clients')
    # ### end Alembic commands ###
