"""refactor chat

Revision ID: 6f71cf15a79f
Revises: e38fde4276ac
Create Date: 2026-04-21 02:57:45.932090

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6f71cf15a79f'
down_revision: Union[str, Sequence[str], None] = 'e38fde4276ac'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chats', sa.Column('is_active', sa.Boolean(), nullable=True))
    op.add_column('chats', sa.Column('reopened_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('chats', 'reopened_at')
    op.drop_column('chats', 'is_active')
    # ### end Alembic commands ###
