"""add bitrix_user_id and token to users

Revision ID: 706ec7eda9e1
Revises: 9e56ba83a36a
Create Date: 2026-05-27 02:47:01.272659

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '706ec7eda9e1'
down_revision: Union[str, Sequence[str], None] = '9e56ba83a36a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('bitrix_access_token', sa.String(length=512), nullable=True))
    op.add_column('users', sa.Column('bitrix_refresh_token', sa.String(length=512), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'bitrix_refresh_token')
    op.drop_column('users', 'bitrix_access_token')
    # ### end Alembic commands ###
