"""add bitrix_user_id to users

Revision ID: 9e56ba83a36a
Revises: fab833ce029d
Create Date: 2026-05-27 02:41:08.692137

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9e56ba83a36a'
down_revision: Union[str, Sequence[str], None] = 'fab833ce029d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('bitrix_user_id', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'bitrix_user_id')
    # ### end Alembic commands ###
