"""fate zone+3

Revision ID: fab833ce029d
Revises: 6f71cf15a79f
Create Date: 2026-04-21 03:58:35.787349

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fab833ce029d'
down_revision: Union[str, Sequence[str], None] = '6f71cf15a79f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ratings', sa.Column('created_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ratings', 'created_at')
    # ### end Alembic commands ###
